app = "godly-open-world"
primary_region = "sin" # Region cố định, ví dụ: Singapore

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/nodejs"]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false # Giữ server luôn chạy
  auto_start_machines = true
  min_machines_running = 1 # Đảm bảo 1 instance duy nhất
  [http_service.checks]
      interval = "15s"
      timeout = "2s"
      grace_period = "5s"
      method = "GET"
      path = "/health"
      
[[services.ports]]
  port = 8080
  handlers = ["tls"]

[mounts]
  source = "data"
  destination = "/data"

[processes]
  app = "node server.js"

# Chống DDoS bằng rate limiting
[http_service.concurrency]
  type = "requests"
  soft_limit = 50
  hard_limit = 100